### ISSUE TITLE
Does chipscopy only support Versal device?

### ISSUE THREAD

**Issue by kele14x** [Xilinx/chipscopy#3]
Hi,

chipscopy looks great and excited. But I'm wonder does ChipScoPy only support Versal devices? Will it support old device such as UltraScale(+), Zynq and 7 Series?

**Comment by mikexilinx** [comment]
Hi @kele14x  - thanks for the feedback! 
Our initial focus is building Versal support in ChipScoPy. We plan to add Ultrascale/US+ support later, possibly as early as the 2021.2 Vivado release. It is unlikely that devices older than US/US+ will be directly supported through this API.

**Comment by julianctrt** [comment]
Hello, I would like to ask also if it's in the roadmap to make this tool available for the RFsoc devices also a estimation date since vivado version 2021.2 is available but still no support for Ultrascale family.

thanks,
Regards.

**Comment by seembha** [comment]
Hi @mikexilinx,
I'm using Chipscopy for US+ GTY transceivers and am loving it. We have another project that uses Zynq US+ GTH transceivers that I would like access with Chipscopy. Do you have any update on when US+ GTH transceivers will be supported? If it is in the works, I would be willing to help test it.
Thank you and Best regards
