### ISSUE TITLE
[Feature request] Add interface to JTAG-to-AXI Master

### ISSUE THREAD

**Issue by outputlogic** [Xilinx/chipscopy#5]
Adding interface to JTAG-to-AXI Master core would greatly enhance chipscopy usability:
  https://www.xilinx.com/products/intellectual-property/jtag_to_axi_master.html
  https://www.xilinx.com/support/documentation/ip_documentation/jtag_axi/v1_2/pg174-jtag-axi.pdf

That interface would allow users to have general-purpose access to design registers.
The interface may look similar to already supported TCL command set to JTAG-to-AXI Master core.

**Comment by mikexilinx** [comment]
ChipScoPy API features are currently available for Versal devices, but JTAG-to-AXI support is a great idea for the future Ultrascale/Ultrascale+ support.  

For Versal, JTAG-AXI functionality through the CIPS IP. The [memory example](https://gitenterprise.xilinx.com/chipscope/chipscopy/blob/master/chipscopy/examples/memory/memory_example.ipynb) shows how to read/write memory in ChipScoPy for general purpose Versal memory access.

Ultrascale/Ultrascale+ ChipScoPy support is a work in progress. Some internal development has been done, but we don't have a definite release plan yet for ChipScoPy.

Some additional information about using CIPS IP for memory access in Versal is in this forum post:
https://support.xilinx.com/s/question/0D52E00006iHjOzSAK/jtag-to-axi-master-ip?language=en_US

We will definitely consider JTAG-to_AXI for US/US+. Thanks for the suggestion!
