### ISSUE TITLE
Can not execute "from chipscopy.api.ddr import DDR"

### ISSUE THREAD

**Issue by AtaraxiaZ** [Xilinx/chipscopy#6]
The code of [2D Eye Scan Tutorial](https://github.com/Xilinx/Vivado-Design-Tutorials/tree/2021.1/Device_Architecture_Tutorials/Versal/NoC_DDRMC/DDRMC_2D_eye_scan) has an error when executing
`from chipscopy.api.ddr import DDR` in scan_util.py. 

The error is 
`ImportError: cannot import name 'DDR' from 'chipscopy.api.ddr' (E:\64bit\anaconda3\lib\site-packages\chipscopy\api\ddr\__init__.py)
`

**Comment by mikexilinx** [comment]
The above "from chipscopy.api.ddr import DDR" error has been forwarded to engineering to investigate.

That specific [2D Eye Scan Tutorial](https://github.com/Xilinx/Vivado-Design-Tutorials/tree/2021.1/Device_Architecture_Tutorials/Versal/NoC_DDRMC/DDRMC_2D_eye_scan) example appears to be written for 2021.1 Xilinx tools. Matching all versions to 2021.1 is a good debugging step.

Installing a specific 2021.1 version of chipscopy is covered in the install guide. Command will be similar to this - 
```
python -m pip install --upgrade chipscopy=="2021.1.*"
```
The 2021.1 hw_server and cs_server are included in all Vivado installations, and can be downloaded from the main xilinx.com website:
https://www.xilinx.com/support/download.html

To get detailed answers to support questions, please visit the [Vivado Debug Tools Board](https://support.xilinx.com/s/topic/0TO2E000000YKYCWA4/vivado-debug-tools). Your questions will be seen by various members of the community and Xilinx employees who can then assist and point you in the right direction.

**Comment by AtaraxiaZ** [comment]
Thanks for your advice. I try the command `chipscopy --hw_url DESKTOP-LMNGRN8:3121 --cs_url DESKTOP-LMNGRN8:3042 report --servers` today and it can run. The output is shown below. The only difference is I open a vivado 2020.2 yesterday and I shut it down today. So I think maybe the opening vivado program can affect the hw_server and cs_server version. However, the error of "from chipscopy.api.ddr import DDR" still exist. I will try your way, Thank you!


                        ChipScoPy Version Information
┌──────────────────────────────────┬──────────────────────────────────────────┐
│                           Entity │ Version                                  │
├──────────────────────────────────┼──────────────────────────────────────────┤
│                        ChipScoPy │ ┌───────────┬──────────────────────┐     │
│                                  │ │ Attribute │ Value                │     │
│                                  │ ├───────────┼──────────────────────┤     │
│                                  │ │     Build │ 2021.2.1639266951    │     │
│                                  │ │ Timestamp │ Dec 12 2021-07:55:51 │     │
│                                  │ └───────────┴──────────────────────┘     │
│                                  │                                          │
│ hw_server @ DESKTOP-LMNGRN8:3121 │ ┌───────────┬──────────────────────────┐ │
│                                  │ │ Attribute │ Value                    │ │
│                                  │ ├───────────┼──────────────────────────┤ │
│                                  │ │    Status │ Connected                │ │
│                                  │ │     Build │ 1634633257               │ │
│                                  │ │   Version │ 2021.2                   │ │
│                                  │ │ Timestamp │ Tue Oct 19 02:47:37 2021 │ │
│                                  │ └───────────┴──────────────────────────┘ │
│                                  │                                          │
│ cs_server @ DESKTOP-LMNGRN8:3042 │ ┌───────────────┬──────────────────────┐ │
│                                  │ │     Attribute │ Value                │ │
│                                  │ ├───────────────┼──────────────────────┤ │
│                                  │ │        Status │ Connected            │ │
│                                  │ │         Build │ 1632779060           │ │
│                                  │ │       Version │ 2021.2.0             │ │
│                                  │ │     Timestamp │ Sep 28 2021-05:44:20 │ │
│                                  │ │       Package │ 2021.2.1632779060    │ │
│                                  │ │ Artifact type │ pyinstaller          │ │
│                                  │ └───────────────┴──────────────────────┘ │
└──────────────────────────────────┴──────────────────────────────────────────┘

**Comment by dkopelove-xilinx** [comment]
Hi @AtaraxiaZ, I wanted to check in with you on this issue and see if the workaround suggested worked for you.
