### ISSUE TITLE
rfsoc support

### ISSUE THREAD

**Issue by julianctrt** [Xilinx/chipscopy#7]
Hello, since the support from now is only available to versal devices and in the roadmap there is plans for the MPsoc devices, I guess the RFsoc family is also includes between these devices.

I'm right?.

Thanks,
regards.

**Comment by dkopelove-xilinx** [comment]
Hi Julian,

Thanks for your inquiry. You are right that support right now is limited to Versal architecture. From the perspective of ChipScoPy RFSoC is the same family as MPSoC. Both of which are part of the UltraScale+ generation. 

I do apologize but UltraScale+ support is not planned at this time.
